import { Scene } from '../Scene';
import { SceneManager } from '../SceneManager';
import { GameMenuScene } from './GameMenuScene';
import { GameState } from '../GameState';

export class WhackAMoleScene implements Scene {
    private sceneManager: SceneManager; private active = -1; private score = 0; private timeLeft = 30; private finished = false; private changeTimer = 0;
    constructor(sceneManager: SceneManager) { this.sceneManager = sceneManager; }
    init(): void { this.reset(); this.sceneManager.getCanvas().addEventListener('pointerup', this.handleInput); }
    private reset() { this.active = Math.floor(Math.random() * 9); this.score = 0; this.timeLeft = 30; this.finished = false; this.changeTimer = 0; }
    private handleInput = (event: PointerEvent) => { const c = this.sceneManager.getCanvas(), r = c.getBoundingClientRect(); const x = (event.clientX - r.left) * c.width / r.width, y = (event.clientY - r.top) * c.height / r.height; if (x < 115 && y < 70) { this.sceneManager.switchScene(new GameMenuScene(this.sceneManager)); return; } if (this.finished) { this.reset(); return; } const size = Math.min(110, c.width / 4), sx = c.width / 2 - size * 1.5, sy = c.height / 2 - size * 1.1; for (let i = 0; i < 9; i++) { const bx = sx + (i % 3) * size, by = sy + Math.floor(i / 3) * size; if (x >= bx && x <= bx + size - 10 && y >= by && y <= by + size - 10 && i === this.active) { this.score++; this.active = Math.floor(Math.random() * 9); this.changeTimer = 0; } } };
    update(deltaTime: number): void { if (this.finished) return; const s = deltaTime / 1000; this.timeLeft -= s; this.changeTimer += s; if (this.changeTimer > 0.85) { this.active = Math.floor(Math.random() * 9); this.changeTimer = 0; } if (this.timeLeft <= 0) { this.timeLeft = 0; this.finished = true; GameState.getInstance().updateHighScore('whack-a-mole', this.score); } }
    draw(ctx: CanvasRenderingContext2D): void { const w = ctx.canvas.width, h = ctx.canvas.height; ctx.fillStyle = '#dff9fb'; ctx.fillRect(0, 0, w, h); ctx.textAlign = 'center'; ctx.fillStyle = '#0984e3'; ctx.font = 'bold 40px "Fredoka One"'; ctx.fillText('Whack-a-Mole', w / 2, 62); ctx.fillStyle = '#2d3436'; ctx.font = 'bold 22px "Nunito"'; ctx.fillText(`Moles: ${this.score}   Time: ${Math.ceil(this.timeLeft)}s`, w / 2, 98); ctx.fillStyle = '#fab1a0'; ctx.fillRect(15, 18, 90, 40); ctx.fillStyle = 'white'; ctx.font = '20px "Nunito"'; ctx.fillText('Back', 60, 45); if (!this.finished) { const size = Math.min(110, w / 4), sx = w / 2 - size * 1.5, sy = h / 2 - size * 1.1; for (let i = 0; i < 9; i++) { const bx = sx + (i % 3) * size, by = sy + Math.floor(i / 3) * size; ctx.fillStyle = '#6c5ce7'; ctx.beginPath(); ctx.ellipse(bx + (size - 10) / 2, by + size - 20, (size - 20) / 2, 18, 0, 0, Math.PI * 2); ctx.fill(); if (i === this.active) { ctx.font = '48px serif'; ctx.fillText('🐹', bx + (size - 10) / 2, by + size - 25); } } } else { ctx.fillStyle = '#2d3436'; ctx.font = 'bold 34px "Fredoka One"'; ctx.fillText(`Great job! ${this.score} moles`, w / 2, h / 2); ctx.font = '22px "Nunito"'; ctx.fillText('Tap to play again', w / 2, h / 2 + 48); } }
    onResize(_width: number, _height: number): void { }
    cleanup(): void { this.sceneManager.getCanvas().removeEventListener('pointerup', this.handleInput); }
}
